plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'io.domainlifecycles.dlc-gradle-plugin' version '3.2.1'
	id 'org.jooq.jooq-codegen-gradle' version '3.20.8'
	id 'org.flywaydb.flyway' version '11.20.0'
}

repositories {
	mavenCentral()
}

group = 'com.esentri'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '21'
}

flyway {
	url = "jdbc:h2:${projectDir}/build/rezeption-db"
	user = 'sa'
	password = ''
	driver = 'org.h2.Driver'
	defaultSchema = 'REZEPTION_FLYWAY'
	createSchemas = true
	encoding = 'UTF-8'
	locations = ["filesystem:${projectDir}/src/main/resources/db/migration"]
}

jooq {
	configuration {
		jdbc {
			driver = 'org.h2.Driver'
			url = "jdbc:h2:${projectDir}/build/rezeption-db"
			user = 'sa'
			password = ''
		}
		generator {
			database {
				name = 'org.jooq.meta.h2.H2Database'
				inputSchema = 'REZEPTION'
			}
			generate {
				daos = false
				pojos = false
			}
			target {
				packageName = 'com.esentri.rezeption.records'
				directory = 'build/generated-sources/jooq'
			}
		}
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dlcGradlePlugin {
	domainModelUpload {
		domainModelPackages = ["com.esentri.rezeption"]
		projectName = "DDD-Hotel-Demo-AI"
		apiKey = "10a3ef8d-1db0-43dd-92ff-e2e340e0c7ef"
		diagramViewerBaseUrl = "https://viewer.domainlifecycles.io"
	}
	serializeMirror {
		fileOutputDir = layout.buildDirectory
		serializations{
			[
			serial		{
						domainModelPackages = ["com.esentri.rezeption"]
					}
			]

		}
	}
	diagram {
		fileOutputDir = layout.buildDirectory
		diagrams {
			diagramSvg {
				domainModelPackages = ["com.esentri.rezeption"]
				format = "svg"
				fileName = "diagram"
				aggregateRootStyle = "fill=#333333 bold"
			}
		}
	}

}

dependencies {
	implementation 'org.jooq:jooq'

	compileOnly 'io.domainlifecycles:dlc-gradle-plugin:3.2.1'
	implementation 'com.h2database:h2:2.4.240'
	implementation 'io.domainlifecycles:spring-boot-starter:3.2.1'
	implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-jooq'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	jooqCodegen 'com.h2database:h2:2.4.240'
	implementation 'org.jmolecules:jmolecules-ddd:1.9.0'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.named("compileJava") {
	dependsOn(tasks.named("jooqCodegen"))
}

tasks.named("jooqCodegen") {
	dependsOn(tasks.named("flywayMigrate"))
	inputs.files(fileTree("src/main/resources/db/migration"))
}

repositories {
    mavenLocal()
}







