plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.4'
	id 'io.domainlifecycles.dlc-gradle-plugin' version '3.1.0'
}

repositories {
	mavenCentral()
}



group = 'com.esentri'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dlcGradlePlugin {
	domainModelUpload {
		domainModelPackages = ["com.esentri.rezeption"]
		projectName = "DDD-Hotel-Demo-AI"
		apiKey = "10a3ef8d-1db0-43dd-92ff-e2e340e0c7ef"
		diagramViewerBaseUrl = "https://viewer.domainlifecycles.io"
	}
	serializeMirror {
		fileOutputDir = layout.buildDirectory
		serializations{
			[
			serial		{
						domainModelPackages = ["com.esentri.rezeption"]
					}
					]

		}
	}
	diagram {
		fileOutputDir = layout.buildDirectory
		diagrams {
			diagramSvg {
				domainModelPackages = ["com.esentri.rezeption"]
				format = "svg"
				fileName = "diagram"
				aggregateRootStyle = "fill=#333333 bold"
			}
		}
	}

}

dependencies {
	compileOnly 'io.domainlifecycles:dlc-gradle-plugin:3.1.0'
	implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework:spring-tx:6.1.3'
    implementation 'io.domainlifecycles:types:3.1.0'
	implementation 'io.domainlifecycles:type-utils:3.1.0'
    implementation 'io.domainlifecycles:assertions:3.1.0'
	implementation 'io.domainlifecycles:domain-events-core:3.1.0'
    implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.domainlifecycles:mirror:3.1.0'
	testImplementation 'io.domainlifecycles:domain-diagrammer:3.1.0'
}

tasks.named('test') {
	useJUnitPlatform()
}



repositories {
    mavenLocal()
}







